### ISSUE TITLE
Don't work.

### ISSUE THREAD

**Issue by Greatwally** [halipso/opskins-helper#1]
Fix please.

**Comment by halipso** [comment]
What do you mean?
You should use this extension via TamperMonkey or GreaseMonkey

**Comment by Greatwally** [comment]
I use TamperMonkey, but can't edit price. Nothing happens after I press "save" button.
Chrome 48.0.2540.0
TamperMonkey 3.11
And same in Vivaldi+TamperMonkey

**Comment by halipso** [comment]
Oh.
Try to open Browse page first then try to edit price.
You should pass CloudFlare Bot Detection.

**Comment by Greatwally** [comment]
POST https://opskins.com/ajax/shop_account.php 403 (Forbidden) 
in console after i press "Save" button.

**Comment by halipso** [comment]
Updated :rofl:

**Comment by renzula** [comment]
how can i use this? i already open it but its not working
